package dk.spoegelsesjaeger

import dk.spoegelsesjaeger.Evidence.DOTS
import dk.spoegelsesjaeger.Evidence.EMF
import dk.spoegelsesjaeger.Evidence.FREEZING
import dk.spoegelsesjaeger.Evidence.ORB
import dk.spoegelsesjaeger.Evidence.SPIRIT_BOX
import dk.spoegelsesjaeger.Evidence.UV
import dk.spoegelsesjaeger.Evidence.WRITING

data class Ghost(
    val name: String,
    val evidence: Set<Evidence>,
    val summary: String,
    val huntText: String,
    /** Highest average sanity at which the ghost can start a hunt on its own. */
    val maxHuntSanity: Int,
    val speedText: String,
    /** Base hunt speeds (m/s) that speed up by up to 65 % while the ghost can see a player. */
    val speeds: List<Double>,
    val tells: List<String>,
    /** Always one of the shown evidences on Nightmare / Insanity. */
    val forced: Evidence? = null,
    /** Shown on top of the real evidence on every difficulty (the Mimic's orbs). */
    val fakeEvidence: Evidence? = null,
    /** Can start a hunt above [maxHuntSanity] through an ability or a single player's sanity. */
    val huntsAtAnySanity: Boolean = false,
    /** Hunt speeds (m/s) that never change with line of sight. */
    val fixedSpeeds: List<Double> = emptyList(),
    /** Copies other ghosts' behaviour, so behaviour-based filters never rule it out. */
    val copiesOthers: Boolean = false,
    val smudgeSeconds: Int = 90,
    val cooldownSeconds: Int = 25,
) {
    val speedClasses: Set<SpeedClass> =
        if (copiesOthers) SpeedClass.entries.toSet() else (speeds + fixedSpeeds).map(SpeedClass::of).toSet()
}

private const val NORMAL_SPEED = "1,7 m/s – bliver op til 65 % hurtigere, mens den kan se dig"
private val NORMAL = listOf(1.7)

object Ghosts {

    val all: List<Ghost> = listOf(
        Ghost(
            name = "Spirit",
            evidence = setOf(EMF, SPIRIT_BOX, WRITING),
            summary = "Et helt almindeligt spøgelse – men røgelse holder det væk ekstra længe.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            smudgeSeconds = 180,
            tells = listOf(
                "Røgelse (smudge) forhindrer jagt i 180 s i stedet for 90 s.",
                "Test: Brug røgelse ved lav sanity og start smudge-timeren. Jager det inden 180 s, er det ikke en Spirit.",
            ),
        ),
        Ghost(
            name = "Wraith",
            evidence = setOf(EMF, SPIRIT_BOX, DOTS),
            summary = "Svæver – rører aldrig salt og kan teleportere hen til en spiller.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Træder aldrig i salt og efterlader derfor aldrig fodspor i salt.",
                "Kan teleportere hen til en tilfældig spiller og efterlade EMF 2 (nogle gange EMF 5) ved gulvet.",
                "Pas på: En rasende Gallu går også gennem salt uden at røre det – men Gallu har UV, det har Wraith ikke.",
            ),
        ),
        Ghost(
            name = "Phantom",
            evidence = setOf(SPIRIT_BOX, UV, DOTS),
            summary = "Dræner sanity, når du er tæt på den – og forsvinder, når du fotograferer den.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Forsvinder, når du tager et foto af den under et event – og spøgelset er ikke med på billedet.",
                "Blinker meget sjældnere synligt under jagter, så den er svær at få øje på.",
                "Dræner sanity hurtigere, når du er tæt på den under events og jagter.",
                "Kan gå hen til en tilfældig spillers position (EMF i hovedhøjde).",
            ),
        ),
        Ghost(
            name = "Poltergeist",
            evidence = setOf(SPIRIT_BOX, UV, WRITING),
            summary = "Kaster med ting – gerne mange på én gang.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Kan kaste mange genstande på én gang (\"eksplosion\"). Hver genstand koster sanity for dem, der ser det.",
                "Kaster en genstand cirka hvert halve sekund under jagter.",
                "Tip: Saml en bunke ting i spøgelsesrummet og hold øje med dem.",
            ),
        ),
        Ghost(
            name = "Banshee",
            evidence = setOf(UV, ORB, DOTS),
            summary = "Udvælger én spiller som sit mål og går efter vedkommende.",
            huntText = "50 % – men det er målets egen sanity, der tæller, ikke gennemsnittet",
            maxHuntSanity = 50,
            huntsAtAnySanity = true,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Kan skrige i parabolmikrofonen – en lyd ingen andre spøgelser laver.",
                "Har altid et kvindenavn. Et mandenavn udelukker Banshee.",
                "Jager kun sit mål, hvis målet er inde i huset – andre kan stå tæt på uden at dø.",
                "Laver oftere syngende events og vandrer hen mod sit mål.",
            ),
        ),
        Ghost(
            name = "Jinn",
            evidence = setOf(EMF, UV, FREEZING),
            summary = "Lynhurtig på lang afstand, så længe strømmen er tændt.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = "1,7 m/s – springer til 2,5 m/s, når strømmen er tændt, og den ser en spiller mere end ca. 3 m væk",
            speeds = NORMAL,
            fixedSpeeds = listOf(2.5),
            tells = listOf(
                "Slukker aldrig selv for strømmen i sikringsskabet.",
                "Evne: Kan dræne 25 % sanity for spillere tæt på, med EMF ved sikringsskabet.",
                "Test: Tænd strømmen og hør efter, om den pludselig bliver meget hurtig, når den ser dig på afstand.",
            ),
        ),
        Ghost(
            name = "Mare",
            evidence = setOf(SPIRIT_BOX, ORB, WRITING),
            summary = "Elsker mørke – jager tidligere, når lyset er slukket.",
            huntText = "60 %, hvis lyset er slukket i rummet den er i – 40 %, hvis det er tændt",
            maxHuntSanity = 60,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Tænder aldrig lyset.",
                "Kan slukke lyset lige efter, at en spiller har tændt det i nærheden af den.",
                "Laver oftere events hvor pærer springer, og vandrer væk fra oplyste rum.",
            ),
        ),
        Ghost(
            name = "Revenant",
            evidence = setOf(ORB, WRITING, FREEZING),
            summary = "Sneglelangsom, mens den leder – ekstremt hurtig, når den har fundet dig.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = "1,0 m/s når den leder – 3,0 m/s, så snart den opdager en spiller; ingen gradvis acceleration",
            speeds = emptyList(),
            fixedSpeeds = listOf(1.0, 3.0),
            tells = listOf(
                "Tydeligt langsomme skridt, der skifter til meget hurtige, når den ser eller hører dig.",
                "Bryd sigtelinjen og gem dig – den falder tilbage til 1,0 m/s, når den når dit sidst kendte sted.",
            ),
        ),
        Ghost(
            name = "Shade",
            evidence = setOf(EMF, WRITING, FREEZING),
            summary = "Genert – laver meget lidt, når der er spillere i nærheden.",
            huntText = "35 %",
            maxHuntSanity = 35,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Kan ikke starte en jagt, mens en spiller er i samme rum som den.",
                "Laver ingen events ved høj sanity og er generelt meget passiv.",
                "Viser sig ofte som en skygge, når den manifesterer sig.",
            ),
        ),
        Ghost(
            name = "Demon",
            evidence = setOf(UV, WRITING, FREEZING),
            summary = "Den mest aggressive – jager tidligt og ofte.",
            huntText = "70 % – og kan i sjældne tilfælde jage ved enhver sanity",
            maxHuntSanity = 70,
            huntsAtAnySanity = true,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            smudgeSeconds = 60,
            cooldownSeconds = 20,
            tells = listOf(
                "Røgelse forhindrer kun jagt i 60 s (normalt 90 s).",
                "Kun 20 s pause mellem jagter (normalt 25 s).",
                "Krucifikset virker på 50 % længere afstand.",
            ),
        ),
        Ghost(
            name = "Yurei",
            evidence = setOf(ORB, FREEZING, DOTS),
            summary = "Smækker døre og dræner sanity.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Evne: Smækker en dør helt i og dræner 15 % sanity for spillere tæt på.",
                "Røgelse fanger den i sit rum i 90 s.",
            ),
        ),
        Ghost(
            name = "Oni",
            evidence = setOf(EMF, FREEZING, DOTS),
            summary = "Meget aktiv og meget synlig.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Laver aldrig tåge-eventet, hvor spøgelset puster en sky mod dig. Pas på: det gående event kan også hvæse.",
                "Er meget mere synlig under jagter end andre spøgelser.",
                "Rører den dig under et event, mister du 20 % sanity (normalt 10 %).",
            ),
        ),
        Ghost(
            name = "Yokai",
            evidence = setOf(SPIRIT_BOX, ORB, DOTS),
            summary = "Tiltrækkes af stemmer – men hører dårligt under jagter.",
            huntText = "50 % – op til 80 %, hvis der tales i nærheden af den",
            maxHuntSanity = 80,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Kan jage allerede ved 80 %, hvis I snakker i dens rum.",
                "Under jagter hører den kun stemmer og elektronik inden for 2,5 m.",
                "Test: Tal under en jagt, når den er tæt på, men uden for sigte – den reagerer ikke.",
            ),
        ),
        Ghost(
            name = "Hantu",
            evidence = setOf(UV, ORB, FREEZING),
            forced = FREEZING,
            summary = "Hurtig i kulde, langsom i varme.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = "Afhænger af temperaturen: 1,4 m/s i varme rum op til 2,7 m/s under frysepunktet; ingen acceleration ved sigtelinje",
            speeds = emptyList(),
            fixedSpeeds = listOf(1.4, 1.75, 2.1, 2.3, 2.4, 2.5, 2.7),
            tells = listOf(
                "Du kan se dens frosne ånde under jagter, når strømmen er slukket.",
                "Tænder aldrig for strømmen – og slukker den oftere end andre.",
                "Farten følger temperaturen i rummet den er i – ikke om den kan se dig.",
            ),
        ),
        Ghost(
            name = "Goryo",
            evidence = setOf(EMF, UV, DOTS),
            forced = DOTS,
            summary = "Kan kun ses gennem D.O.T.S. på kamera.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "D.O.T.S. ses kun på videokamera – og kun når ingen spillere er i rummet.",
                "Bevæger sig kun kort væk fra sit rum og skifter aldrig favoritrum.",
            ),
        ),
        Ghost(
            name = "Myling",
            evidence = setOf(EMF, UV, WRITING),
            summary = "Lydløs under jagter, men larmende resten af tiden.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Dens skridt og stemme under jagter kan kun høres inden for ca. 12 m (normalt 20 m).",
                "Laver oftere lyde i parabolmikrofonen.",
                "Test: Hører du først skridtene, når den er tæt på dig, er det sandsynligvis en Myling.",
            ),
        ),
        Ghost(
            name = "Onryo",
            evidence = setOf(SPIRIT_BOX, ORB, FREEZING),
            summary = "Hader ild – og kan jage, når den puster flammer ud.",
            huntText = "60 % (40 % tæt på en brændende flamme) – og kan jage ved enhver sanity efter hver tredje flamme den puster ud",
            maxHuntSanity = 60,
            huntsAtAnySanity = true,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "En tændt flamme inden for 4 m virker som et krucifiks – og bruges før krucifikset.",
                "Hver tredje flamme den puster ud kan udløse en jagt, uanset sanity.",
                "Puster lys ud oftere end andre spøgelser.",
            ),
        ),
        Ghost(
            name = "The Twins",
            evidence = setOf(EMF, SPIRIT_BOX, FREEZING),
            summary = "To spøgelser i ét – interaktioner to steder på én gang.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = "1,5 eller 1,9 m/s (tilfældigt fra jagt til jagt) – bliver hurtigere, mens den kan se dig",
            speeds = listOf(1.5, 1.9),
            tells = listOf(
                "To interaktioner kort efter hinanden, eller et stykke fra hvor spøgelset er.",
                "Jagter skifter mellem lidt langsom og lidt hurtig.",
                "Kan forveksles med Obambo (1,45 / 1,96 m/s).",
            ),
        ),
        Ghost(
            name = "Raiju",
            evidence = setOf(EMF, ORB, DOTS),
            summary = "Lever af elektronik – hurtig og tidlig nær tændt udstyr.",
            huntText = "50 % – 65 %, når der er tændt elektronik i nærheden",
            maxHuntSanity = 65,
            speedText = "1,7 m/s – 2,5 m/s i nærheden af tændt elektronik",
            speeds = NORMAL,
            fixedSpeeds = listOf(2.5),
            tells = listOf(
                "Forstyrrer elektronik på længere afstand (15 m i stedet for 10 m).",
                "Bliver pludselig hurtig, når den kommer tæt på tændt udstyr under en jagt.",
                "Test: Læg tændt udstyr på dens rute og hør, om farten ændrer sig.",
            ),
        ),
        Ghost(
            name = "Obake",
            evidence = setOf(EMF, UV, ORB),
            forced = UV,
            summary = "Formskifter – og efterlader mærkelige fingeraftryk.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = NORMAL_SPEED,
            speeds = NORMAL,
            tells = listOf(
                "Kan efterlade et seks-fingret håndaftryk eller dobbelte aftryk på kontakter.",
                "Skifter udseende i et enkelt blink under jagter.",
                "25 % chance for slet ingen aftryk, og aftrykkene forsvinder dobbelt så hurtigt.",
            ),
        ),
        Ghost(
            name = "The Mimic",
            evidence = setOf(SPIRIT_BOX, UV, FREEZING),
            fakeEvidence = ORB,
            summary = "Efterligner andre spøgelser – og viser altid falske Ghost Orbs.",
            huntText = "Som det spøgelse, den efterligner lige nu",
            maxHuntSanity = 100,
            huntsAtAnySanity = true,
            speedText = "Som det spøgelse, den efterligner lige nu",
            speeds = emptyList(),
            copiesOthers = true,
            tells = listOf(
                "Viser altid Ghost Orbs som et ekstra, falsk bevis – også på Nightmare, Insanity og uden beviser.",
                "Spirit Box + Ultraviolet + Freezing + Ghost Orb (fire beviser) er altid en Mimic.",
                "Et komplet sæt for Hantu, Onryo eller Kormos udelukker ikke Mimic – led efter det fjerde bevis.",
                "Skifter hvilket spøgelse den efterligner hvert 30.–120. sekund.",
            ),
        ),
        Ghost(
            name = "Moroi",
            evidence = setOf(SPIRIT_BOX, WRITING, FREEZING),
            forced = SPIRIT_BOX,
            summary = "Forbander spillere – og bliver hurtigere, jo lavere sanity.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = "1,5 m/s ved høj sanity op til 2,25 m/s ved lav sanity – plus acceleration, mens den kan se dig",
            speeds = listOf(1.5, 1.583, 1.66, 1.749, 1.832, 1.915, 1.998, 2.081, 2.164, 2.25),
            tells = listOf(
                "Kan forbande dig gennem spirit boxen eller parabolmikrofonen. Forbandelsen fordobler dit sanity-tab – sanity-piller fjerner den.",
                "Bliver hurtigere, jo lavere den gennemsnitlige sanity er – også midt i en jagt.",
                "Røgelse blænder den i ca. 7 s under en jagt (normalt 5 s).",
            ),
        ),
        Ghost(
            name = "Deogen",
            evidence = setOf(SPIRIT_BOX, WRITING, DOTS),
            forced = SPIRIT_BOX,
            summary = "Ved altid, hvor du er – men er meget langsom tæt på.",
            huntText = "40 %",
            maxHuntSanity = 40,
            speedText = "3,0 m/s langt fra sit mål, 0,4 m/s tæt på; ingen acceleration ved sigtelinje",
            speeds = emptyList(),
            fixedSpeeds = listOf(0.4, 3.0),
            tells = listOf(
                "Ved altid hvor spillerne er – det nytter ikke at gemme sig.",
                "Kan lave en tyrelignende snøften i spirit boxen, når du står helt tæt på den.",
                "Løb i ring om den: tæt på er den ekstremt langsom.",
            ),
        ),
        Ghost(
            name = "Thaye",
            evidence = setOf(ORB, WRITING, DOTS),
            summary = "Ældes i løbet af opgaven – aktiv og hurtig i starten, langsom til sidst.",
            huntText = "75 % som ung – falder 6 % hver gang den ældes, ned til 15 %",
            maxHuntSanity = 75,
            speedText = "2,75 m/s som ung, ned til 1,0 m/s som gammel; ingen acceleration ved sigtelinje",
            speeds = emptyList(),
            fixedSpeeds = (0..10).map { 2.75 - 0.175 * it },
            tells = listOf(
                "Ældes hvert 1.–2. minut, når der er spillere tæt på den.",
                "Meget hurtig og tidlig første jagt – bliver langsommere og mere passiv over tid.",
                "Spørg om alderen på Ouija-brættet: svaret stiger i løbet af opgaven.",
            ),
        ),
        Ghost(
            name = "Dayan",
            evidence = setOf(EMF, ORB, SPIRIT_BOX),
            summary = "Reagerer på bevægelse: bliver stærkere, når du bevæger dig tæt på den.",
            huntText = "50 % – 65 %, hvis en spiller inden for 10 m bevæger sig, 45 % hvis de står stille",
            maxHuntSanity = 65,
            speedText = "1,7 m/s på afstand – inden for 10 m: 2,25 m/s, hvis nogen bevæger sig, 1,2 m/s hvis alle står stille",
            speeds = NORMAL,
            fixedSpeeds = listOf(1.2, 2.25),
            tells = listOf(
                "Stå helt stille, når den er tæt på under en jagt – den bliver meget langsom. Tag et skridt, og den bliver hurtig.",
                "Har altid et kvindenavn. Et mandenavn udelukker Dayan.",
                "Kan jage tidligt, hvis I går meget rundt i nærheden af den.",
            ),
        ),
        Ghost(
            name = "Gallu",
            evidence = setOf(EMF, UV, SPIRIT_BOX),
            summary = "Bliver rasende af beskyttelsesudstyr – og udmattet bagefter.",
            huntText = "50 % normalt – 60 % når den er rasende, 40 % når den er svækket",
            maxHuntSanity = 60,
            speedText = "1,7 m/s normalt – 1,96 m/s rasende, 1,36 m/s svækket (plus acceleration)",
            speeds = listOf(1.36, 1.7, 1.96),
            tells = listOf(
                "Krucifiks, røgelse og salt gør den mere rasende. Slutter en jagt, mens den er rasende, bliver den svækket.",
                "Rasende: går gennem salt uden at røre det, røgelse blænder kun 4 s, og krucifikset har kortere rækkevidde.",
                "Svækket: tydeligt langsom jagt (under gå-hastighed), og røgelse blænder 6 s.",
                "Ligner en Wraith i salt – men Gallu har UV, det har Wraith ikke.",
            ),
        ),
        Ghost(
            name = "Obambo",
            evidence = setOf(UV, WRITING, DOTS),
            summary = "Skifter mellem en rolig og en aggressiv tilstand.",
            huntText = "10 % når den er rolig – 65 % når den er aggressiv",
            maxHuntSanity = 65,
            speedText = "1,45 m/s rolig, 1,96 m/s aggressiv – kan skifte midt i en jagt",
            speeds = listOf(1.45, 1.96),
            tells = listOf(
                "Starter rolig. Skifter første gang 1 minut efter, at hoveddøren åbnes, og derefter hvert 2. minut.",
                "Rolig: meget aktiv og let at spore. Aggressiv: stille – og jager tidligt.",
                "Farten kan skifte midt i en jagt. Jagter startet i aggressiv tilstand er 20 % kortere.",
                "Kan forveksles med The Twins (1,5 / 1,9 m/s).",
            ),
        ),
        Ghost(
            name = "Kormos",
            evidence = setOf(ORB, SPIRIT_BOX, UV),
            summary = "Blind – finder dig på lyden af dine skridt.",
            huntText = "50 % – op til 70 %, hvis en spiller løber i dens rum",
            maxHuntSanity = 70,
            speedText = "1,7 m/s – 2,21 m/s når den går mod en lyd; ser kun spillere inden for 5 m",
            speeds = listOf(1.7, 2.21),
            tells = listOf(
                "Hører skridt under jagter: listende inden for 10 m, gående 15 m og løbende 30 m (samme etage).",
                "Står du helt stille og tavs, kan den ikke finde dig – den kan gå lige forbi dig.",
                "Laver aldrig tåge-eventet eller jagende events.",
                "Kan dræbe dig ved at gå ind i dig, også uden sigtelinje.",
            ),
        ),
        Ghost(
            name = "Aswang",
            evidence = setOf(FREEZING, WRITING, DOTS),
            summary = "Accelererer lynhurtigt – men kan ikke dræbe dig i et skjulested.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = "1,53 m/s – når op på ca. 2,5 m/s efter ca. 9 s med sigtelinje (normalt 13 s)",
            speeds = listOf(1.53),
            tells = listOf(
                "Kan ikke dræbe en spiller, der gemmer sig i et rigtigt skjulested (skab, garderobe, telt) – jagten slutter i stedet.",
                "Næste jagt starter derefter med at gå direkte til skjulestedet – uden den sædvanlige frist.",
                "Lidt langsom grundfart, men accelererer meget hurtigt, når den ser dig.",
            ),
        ),
        Ghost(
            name = "Deildegast",
            evidence = setOf(EMF, WRITING, DOTS),
            summary = "Starter ekstremt hurtig – bliver langsommere, jo flere ting I rører ved.",
            huntText = "50 %",
            maxHuntSanity = 50,
            speedText = "3,0 m/s minus 0,1 m/s for hver ting I har rørt siden sidste jagt (mindst 0,4 m/s); samme fart hele jagten",
            speeds = emptyList(),
            fixedSpeeds = (0..26).map { 3.0 - 0.1 * it },
            tells = listOf(
                "Samme fart hele jagten – ingen acceleration, når den ser dig.",
                "Tæller: ting I samler op (ikke udstyr), lyskontakter, sikringsskab, vandhaner, mikrobølgeovne osv. Døre og forbandede genstande tæller ikke.",
                "Farten nulstilles til 3,0 m/s efter hver jagt – også når et krucifiks stopper den.",
                "Test: Flyt 10–15 forskellige ting – den næste jagt bør være tydeligt langsommere.",
            ),
        ),
    )

    fun byName(name: String): Ghost? = all.firstOrNull { it.name == name }
}
